branches:
  only:
  - pelican
language: python
python:
- '3.5'
before_install:
- sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-de language-pack-pt_BR
- openssl aes-256-cbc -K $encrypted_36812bacabfa_key -iv $encrypted_36812bacabfa_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git clone git@github.com:rtancman/pelican-bootstrap3-rtancman-yeti.git
- git remote set-url origin git@github.com:rtancman/rtancman.github.io.git
- git fetch origin -f master:master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pelican-themes --install ./pelican-bootstrap3-rtancman-yeti
script:
- make github